apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: deployer
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      manifest:
        type: string
        required: true
  workflow_dispatch:
jobs:
  demo-go-service-demo-go-service-sv-gha-2:
    if: ${{ fromJSON(inputs.manifest)['demo-go-service']['demo-go-service-sv-gha-2'].deploy }}
    uses: cloudbees-compliance/demo-go-service/.cloudbees/workflows/deploy.yaml
    with:
      artifact-id: ${{ fromJSON(inputs.manifest)['demo-go-service']['demo-go-service-sv-gha-2'].id }}
      environment: ${{ inputs.environment }}
